"""Compute forum-thread mining status.

Counts how many forum threads in `corpus/forum/printpage-*.html`
have been referenced from at least one insight card or article,
and writes a markdown report to `insights/MINING_STATUS.md`.

Usage:
    python scripts/forum_mining_status.py
"""
import datetime
import glob
import os
import re
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent

    # Collect every forum topic ID referenced from an insight card,
    # article, or reference index.
    referenced: set[int] = set()
    for pattern in (
        "insights/insight-*.md",
        "docs/**/*.md",
        "insights/SMALL_THREADS_REFERENCE_INDEX.md",
        "insights/TINY_THREADS_REFERENCE_INDEX.md",
    ):
        for f in repo_root.glob(pattern):
            text = f.read_text()
            referenced.update(int(m.group(1)) for m in re.finditer(r"topic=(\d+)", text))

    # Load the skip list — threads evaluated and rejected.
    skip_list: set[int] = set()
    skip_file = repo_root / "insights" / ".mining_skip_list.txt"
    if skip_file.exists():
        for line in skip_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            tid = line.split()[0]
            if tid.isdigit():
                skip_list.add(int(tid))

    # Bucket every printpage HTML file by size.
    buckets = {"≥50KB": [], "30–50KB": [], "15–30KB": [], "5–15KB": [], "<5KB": []}
    forum_dir = repo_root / "corpus" / "forum"
    for f in sorted(forum_dir.glob("printpage-*.html")):
        size = f.stat().st_size
        topic_m = re.search(r"printpage-(\d+)", f.name)
        topic_id = int(topic_m.group(1).lstrip("0") or "0")
        is_mined = topic_id in referenced
        is_skipped = topic_id in skip_list

        if size >= 50_000:
            bucket = "≥50KB"
        elif size >= 30_000:
            bucket = "30–50KB"
        elif size >= 15_000:
            bucket = "15–30KB"
        elif size >= 5_000:
            bucket = "5–15KB"
        else:
            bucket = "<5KB"
        buckets[bucket].append((size, topic_id, f.name, is_mined, is_skipped))

    today = datetime.date.today().isoformat()
    lines = [
        "# Forum mining status",
        "",
        f"*Auto-generated by `scripts/forum_mining_status.py`. Last refreshed: {today}.*",
        "",
        "Tracks how many forum threads in `corpus/forum/` have been mined into",
        "an insight card or referenced directly from an article. A thread is",
        "considered \"mined\" if any insight or article cites its `topic=N` ID.",
        "Threads listed in `insights/.mining_skip_list.txt` (evaluated and",
        "rejected as case-specific / narrow / historical) are excluded from",
        "the priority queue but counted separately.",
        "",
        "## Summary",
        "",
        "| Size bucket | Total | Mined | Skipped | Unmined | Mining ratio |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    g_total = g_mined = g_skipped = 0
    for label in ["≥50KB", "30–50KB", "15–30KB", "5–15KB", "<5KB"]:
        rows = buckets[label]
        total = len(rows)
        mined = sum(1 for r in rows if r[3])
        skipped = sum(1 for r in rows if r[4] and not r[3])
        unmined = total - mined - skipped
        ratio = (mined / total * 100) if total else 0
        g_total += total
        g_mined += mined
        g_skipped += skipped
        lines.append(f"| {label} | {total} | {mined} | {skipped} | {unmined} | {ratio:.1f}% |")
    g_unmined = g_total - g_mined - g_skipped
    g_ratio = (g_mined / g_total * 100) if g_total else 0
    lines.append(f"| **Total** | **{g_total}** | **{g_mined}** | **{g_skipped}** | **{g_unmined}** | **{g_ratio:.1f}%** |")
    lines.append("")
    lines.append(f"*Distinct mined topic IDs: {len(referenced)}.*")
    lines.append(f"*Skipped topic IDs (no actionable findings): {len(skip_list)}.*")
    lines.append("")
    lines.append("## Priority queue (largest unmined, unskipped threads)")
    lines.append("")
    lines.append("Top 20 unmined threads by file size, excluding the skip list.")
    lines.append("These are the highest-density candidates for the next mining pass.")
    lines.append("")
    lines.append("| Size | Topic ID | File |")
    lines.append("|---:|---:|---|")
    big_unmined = []
    for rows in buckets.values():
        big_unmined.extend([r for r in rows if not r[3] and not r[4]])
    big_unmined.sort(key=lambda r: -r[0])
    for size, topic_id, name, _, _ in big_unmined[:20]:
        size_kb = size // 1024
        lines.append(f"| {size_kb}KB | {topic_id} | `{name}` |")

    out = repo_root / "insights" / "MINING_STATUS.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}")
    print()
    print(f"Total threads:        {g_total}")
    print(f"Mined:                {g_mined} ({g_ratio:.1f}%)")
    print(f"Skipped (no value):   {g_skipped}")
    print(f"Unmined:              {g_unmined}")
    print(f"≥30KB unmined queue:  {sum(1 for r in (buckets['≥50KB'] + buckets['30–50KB']) if not r[3] and not r[4])}")
    print(f"≥15KB unmined queue:  {sum(1 for r in (buckets['≥50KB'] + buckets['30–50KB'] + buckets['15–30KB']) if not r[3] and not r[4])}")


if __name__ == "__main__":
    main()
